on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: bionic R-CMD-check

jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/verse:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install apt-get packages
        run: |-
          sudo apt-get update
          sudo apt-get install -y libmagick++ texlive-latex-extra
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), "depends.Rds", version = 2)
        shell: Rscript {0}
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: Rscript -e 'Sys.getenv("R_LIBS_USER")'
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-
      - name: Install dependencies
        run: |
          library(remotes)
          deps <- readRDS("depends.Rds")
          deps[["installed"]] <- vapply(deps[["package"]],remotes:::local_sha, character(1))
          update(deps)
        shell: Rscript {0}
      - name: Build and check
        run: |
          R CMD build .
          R CMD check *.tar.gz
          R CMD install .